# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.IntegerField(unique=True)),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('stock_symbol', models.CharField(max_length=5)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('trade_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='trades',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestAPI.User'),
        ),
    ]
