# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('stock_symbol', models.CharField(max_length=5)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trade_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestAPI.User'),
        ),
    ]
