# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='stock_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
