# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0002_auto_20180224_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.IntegerField(unique=True)),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('stock_symbol', models.CharField(max_length=5)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trade_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestAPI.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='trades',
            name='user',
        ),
        migrations.DeleteModel(
            name='Trades',
        ),
    ]
