# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0002_auto_20180228_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='stock_price',
            field=models.FloatField(),
        ),
    ]
