# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0003_auto_20180225_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='trade_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='trade',
            name='id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
